[package]
name = "shadow-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shadow"
path = "src/main.rs"

[dependencies]
serde_json = { workspace = true }
rpassword = { workspace = true }
rusqlite = { workspace = true }
tokio = { workspace = true }
shadow-core = { path = "../shadow-core" }
shadow-server = { path = "../shadow-server" }
